import React from 'react'
export const REG_USER = 'USER/REG_USER'
export const LOGIN_USER = 'USER/LOGIN_USER'
export const ACTIVE_USER = 'USER/ACTIVE_USER'
export const UPDATE_USER = 'USER/UPDATE_USER'